###Cola A
POST http://localhost:8080/rabbitmq/event
Content-Type: application/json

{
    "id":1,
    "name":"Event A",
    "edad":11
}
###Cola B

POST http://localhost:8080/rabbitmq/event
Content-Type: application/json

{
    "id":1,
    "name":"Event B",
    "edad":-1
}

###Event A y B van a cola C